/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Cliente;
import Dominio.Cuenta;
import Dominio.Operacion;
import Dominio.Transferencia;
import Excepciones.PersistenciaException;
import Interfaces.IClientesDAO;
import Interfaces.ICuentasDAO;
import Interfaces.IDomicilioDAO;
import Interfaces.IOperacionesDAO;
import Interfaces.ITransferenciasDAO;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel Lopez
 */
public class frmTransferencia extends javax.swing.JFrame {

    private final Cliente cliente;
    private final IClientesDAO clientesDAO;
    private final ICuentasDAO cuentasDAO;
    private final ITransferenciasDAO transferenciasDAO;
    private final IOperacionesDAO operacionesDAO;
    private final IDomicilioDAO domicilioDAO;
    private static final Logger LOG = Logger.getLogger(frmInterfazCliente.class.getName());

    public frmTransferencia(Cliente cliente, IClientesDAO clientesDAO, ICuentasDAO cuentasDAO, ITransferenciasDAO transferenciasDAO, IOperacionesDAO operacionesDAO, IDomicilioDAO domicilioDAO) {
        this.cliente = cliente;
        this.clientesDAO = clientesDAO;
        this.cuentasDAO = cuentasDAO;
        this.transferenciasDAO = transferenciasDAO;
        this.operacionesDAO = operacionesDAO;
        this.domicilioDAO = domicilioDAO;
        initComponents();
        cargarComboBox();

    }

    public void cargarComboBox() {
        int cuentas;
        this.cbxCuentas.removeAllItems();
        try {
            List<Cuenta> listaCuentas = this.cuentasDAO.consultarListaCuentas(cliente);
            for (Cuenta cuenta : listaCuentas) {
                cuentas = cuenta.getNum_cuenta();
                this.cbxCuentas.addItem(String.valueOf(cuentas));
            }
        } catch (PersistenciaException ex) {
            LOG.log(Level.SEVERE, ex.getMessage());
        }
    }

    public void realizarTransferencia() {
        int cbxCuentaOrigen = parseInt(this.cbxCuentas.getItemAt(this.cbxCuentas.getSelectedIndex()));
        int cuentaDestino = parseInt(this.txtCuentaDestino.getText());
        float montoTransferencia = Float.parseFloat(this.txtSaldo.getText());
        try {
            int folio = transferenciasDAO.realizarTransferencia(cbxCuentaOrigen, cuentaDestino, montoTransferencia);
            Transferencia transferencia = new Transferencia(folio, cuentaDestino);
            transferenciasDAO.insertar(transferencia);
            JOptionPane.showMessageDialog(this, "Se realizo la transaccion correctamente");
            new frmInterfazCliente(cliente, clientesDAO, cuentasDAO, transferenciasDAO, operacionesDAO, domicilioDAO).setVisible(true);
            this.dispose();
        } catch (PersistenciaException ex) {
            Logger.getLogger(frmTransferencia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNumeroCuentaDestino = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtCuentaDestino = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        lblCuentaOrigen = new javax.swing.JLabel();
        cbxCuentas = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transferencia");
        setResizable(false);

        jLabel1.setText("Transferencia de Saldo");

        lblNumeroCuentaDestino.setText("Cuenta Destino");

        lblSaldo.setText("Saldo a enviar");

        txtCuentaDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuentaDestinoKeyTyped(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblCuentaOrigen.setText("Cuenta Origen");

        cbxCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(186, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroCuentaDestino)
                            .addComponent(lblCuentaOrigen)
                            .addComponent(lblSaldo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSaldo)
                            .addComponent(txtCuentaDestino)
                            .addComponent(cbxCuentas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuentaOrigen)
                    .addComponent(cbxCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnCancelar))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        realizarTransferencia();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        frmInterfazCliente interfaz = new frmInterfazCliente(cliente, clientesDAO, cuentasDAO, transferenciasDAO, operacionesDAO, domicilioDAO);
        interfaz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCuentaDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaDestinoKeyTyped
        char txt = evt.getKeyChar();
        if (!(Character.isDigit(txt))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCuentaDestinoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cbxCuentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCuentaOrigen;
    private javax.swing.JLabel lblNumeroCuentaDestino;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtCuentaDestino;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
